version: 0.4.{build}
image: Visual Studio 2019
before_build:
  - ps: >-
      dotnet tool restore

      dotnet paket restore
build_script:
  - ps: >-
      dotnet build -c release

      dotnet paket pack src/Iride --version $env:APPVEYOR_BUILD_VERSION
test_script:
  - ps: dotnet test -c release
artifacts:
  - path: src\Iride\*.nupkg
    name: nuget

deploy:
  on:
    branch: master
  provider: NuGet
  api_key:
    secure: WZoSUjLHOWIabe+DORILuSbUApqeaXBfyPoD2w8CgTBuXcD9jevv2dP2EnxX4U0s
  skip_symbols: true
  artifact: /.*\.nupkg/
